name: Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - main  # Se ejecuta cada vez que haya cambios en main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Generar build
        run: npm run build

      - name: Desplegar en GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
